-- ==========================================
-- CUSTOMERS TABLES
-- ==========================================

CREATE TABLE IF NOT EXISTS customer_identifier (
  customer_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_email varchar(255) NOT NULL UNIQUE,
  customer_phone_number varchar(255) NOT NULL,
  customer_added_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  customer_hash varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS customer_info (
  customer_info_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id INT NOT NULL REFERENCES customer_identifier(customer_id), 
  customer_first_name varchar(255) NOT NULL,
  customer_last_name varchar(255) NOT NULL,
  active_customer_status INT NOT NULL
);

CREATE TABLE IF NOT EXISTS customer_vehicle_info (
  vehicle_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id INT NOT NULL REFERENCES customer_identifier(customer_id), 
  vehicle_year INT NOT NULL,
  vehicle_make varchar(255) NOT NULL,
  vehicle_model varchar(255) NOT NULL,
  vehicle_type varchar(255) NOT NULL,
  vehicle_mileage INT NOT NULL, 
  vehicle_tag varchar(255) NOT NULL,
  vehicle_serial varchar(255) NOT NULL,
  vehicle_color varchar(255) NOT NULL
);

-- ==========================================
-- COMPANY TABLES
-- ==========================================

CREATE TABLE IF NOT EXISTS company_roles (
  company_role_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_role_name varchar(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS common_services (
  service_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_name varchar(255) NOT NULL,
  service_description TEXT
);

-- ==========================================
-- EMPLOYEE TABLES
-- ==========================================

CREATE TABLE IF NOT EXISTS employee (
  employee_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_email varchar(255) NOT NULL UNIQUE,
  active_employee INT NOT NULL,
  added_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS employee_info (
  employee_info_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id INT NOT NULL REFERENCES employee(employee_id),
  employee_first_name varchar(255) NOT NULL,
  employee_last_name varchar(255) NOT NULL,
  employee_phone varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS employee_pass (
  employee_pass_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id INT NOT NULL REFERENCES employee(employee_id),
  employee_password_hashed varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS employee_role (
  employee_role_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id INT NOT NULL REFERENCES employee(employee_id),
  company_role_id INT NOT NULL REFERENCES company_roles(company_role_id)
);

-- ==========================================
-- ORDER TABLES
-- ==========================================

CREATE TABLE IF NOT EXISTS orders (
  order_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id INT NOT NULL REFERENCES employee(employee_id),
  customer_id INT NOT NULL REFERENCES customer_identifier(customer_id),
  vehicle_id INT NOT NULL REFERENCES customer_vehicle_info(vehicle_id),
  order_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  active_order INT NOT NULL,
  order_hash varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS order_info (
  order_info_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INT NOT NULL REFERENCES orders(order_id),
  order_total_price INT NOT NULL,
  estimated_completion_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  completion_date TIMESTAMPTZ,
  additional_request TEXT,
  notes_for_internal_use TEXT,
  notes_for_customer TEXT,
  additional_requests_completed INT NOT NULL
);

CREATE TABLE IF NOT EXISTS order_services (
  order_service_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INT NOT NULL REFERENCES orders(order_id),
  service_id INT NOT NULL REFERENCES common_services(service_id),
  service_completed INT NOT NULL
);

CREATE TABLE IF NOT EXISTS order_status (
  order_status_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INT NOT NULL REFERENCES orders(order_id),
  order_status INT NOT NULL
);

-- ==========================================
-- AUTOMATIC UPDATE TRIGGERS (Replaces ON UPDATE)
-- ==========================================

-- Trigger function for customer_identifier
CREATE OR REPLACE FUNCTION trigger_set_customer_added_date()
RETURNS TRIGGER AS $$
BEGIN
  NEW.customer_added_date = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_customer_added_date
BEFORE UPDATE ON customer_identifier
FOR EACH ROW
EXECUTE FUNCTION trigger_set_customer_added_date();

-- Trigger function for employee
CREATE OR REPLACE FUNCTION trigger_set_employee_added_date()
RETURNS TRIGGER AS $$
BEGIN
  NEW.added_date = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_employee_added_date
BEFORE UPDATE ON employee
FOR EACH ROW
EXECUTE FUNCTION trigger_set_employee_added_date();

-- ==========================================
-- SEED DATA INSERTS
-- ==========================================

-- Add the roles to the database 
INSERT INTO company_roles (company_role_name)
VALUES ('Employee'), ('Manager'), ('Admin');

-- This is the admin account 
INSERT INTO employee (employee_email, active_employee, added_date)
VALUES ('admin@admin.com', 1, CURRENT_TIMESTAMP);

INSERT INTO employee_info (employee_id, employee_first_name, employee_last_name, employee_phone)
VALUES (1, 'Admin', 'Admin', '555-555-5555'); 

-- Password is 123456
INSERT INTO employee_pass (employee_id, employee_password_hashed)
VALUES (1, '$2b$10$7vB.9s5f.mR7GvY8uL7vHeL0P1v6fQzQ9Z1v6fQzQ9Z1v6fQzQ9Z');  

INSERT INTO employee_role (employee_id, company_role_id)
VALUES (1, 3);